[package]
name = "fulu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.15.0"
rfd = "0.6.2"
futures = "0.3.19"
recipeapi = {path = "./recipeapi"}
