collection_name = "Various Vegan Recipes"

[[recipes]]
recipe_name = "Waffles"
cooking_time = 30
description = "Very Tasty Waffles"

[recipes.ingredients]
Milk = "300ml"
Backpulver = "1 Päckchen"
Eggs = "2"
Flour = "200g"

[[recipes]]
recipe_name = "Gin Tonic"
cooking_time = 30
description = "Strong Alcohol"

[recipes.ingredients]
Gin = "2cl"
Grapefruit = "2 sclices"
Tonic = "2cl"
